# Generated by Django 5.1.4 on 2026-02-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('in_use', 'In Use'), ('maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
